import * as vscode from 'vscode';
import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs';
import { ParserService } from '../services/parserService';
import { AnalysisOptions, AnalyzerService } from '../services/analyzerService';
import { DiscoveryService } from '../services/discoveryService';
import { SessionDetail } from '../types/models';

/**
 * Whether the Steps/Analysis/... tab bar and the Steps search bar are folded
 * away. Kept in the extension's global state (VS Code's own storage), like the
 * session list's project filter, so they survive reloads and apply in every
 * window.
 */
const TABS_COLLAPSED_KEY = 'argus.session.tabsCollapsed';
const SEARCH_COLLAPSED_KEY = 'argus.session.searchCollapsed';

/**
 * Attachment names are generated by the parser, but they arrive here from the
 * webview, so they are treated as untrusted: a name is a single path segment
 * of safe characters, never a traversal into somewhere else on disk.
 */
function safeFileName(name: unknown): string {
  const base = typeof name === 'string' ? path.basename(name) : '';
  const cleaned = base.replace(/[^\w.-]/g, '_').replace(/^\.+/, '');
  return cleaned || 'attachment.bin';
}

export class SessionWebviewProviderReact {
  private panels: Map<string, vscode.WebviewPanel> = new Map();
  private watchers: Map<string, fs.FSWatcher> = new Map();
  private subagentWatchers: Map<string, fs.FSWatcher> = new Map();

  constructor(
    private context: vscode.ExtensionContext,
    private discoveryService: DiscoveryService,
    private parserService: ParserService,
    private analyzerService: AnalyzerService
  ) {
    // Push settings.json edits into already-open sessions; otherwise a changed
    // autoExpand/sort default only takes effect on the next panel.
    context.subscriptions.push(
      vscode.workspace.onDidChangeConfiguration(e => {
        if (
          !e.affectsConfiguration('argus.steps') &&
          !e.affectsConfiguration('argus.notes')
        ) {
          return;
        }
        const data = this.getUiConfig();
        for (const panel of this.panels.values()) {
          panel.webview.postMessage({ type: 'config', data });
        }
      })
    );
  }

  async openSessionDetail(sessionId: string): Promise<void> {
    return this.openSessionTab(sessionId, 'overview');
  }

  async openSessionTab(sessionId: string, tabType: string): Promise<void> {
    const panelKey = `${sessionId}`;

    // Check if panel already exists
    const existingPanel = this.panels.get(panelKey);
    if (existingPanel) {
      existingPanel.reveal();
      return;
    }

    // Load session data
    const sessionData = await this.loadSessionData(sessionId);
    if (!sessionData) {
      vscode.window.showErrorMessage('Failed to load session data');
      return;
    }

    // Create webview panel
    const panel = vscode.window.createWebviewPanel(
      'argusSession',
      `${(sessionData.aiTitle || sessionData.prompt).substring(0, 30)}...`,
      this.getViewColumn(),
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [
          vscode.Uri.file(path.join(this.context.extensionPath, 'out', 'webview')),
        ],
      }
    );

    // Set HTML content
    panel.webview.html = this.getWebviewContent(panel.webview);

    // Send user settings before the data, so the UI mounts with the configured
    // sort order instead of flipping right after the first render
    panel.webview.postMessage({
      type: 'config',
      data: this.getUiConfig(),
    });

    // Send session data to webview
    panel.webview.postMessage({
      type: 'sessionData',
      data: sessionData,
    });

    // Send top-level directory listing for the session cwd
    this.sendDirectoryTree(panel, sessionData.project);

    // Handle messages from webview
    panel.webview.onDidReceiveMessage(
      async (message) => {
        switch (message.type) {
          case 'ready':
            // Webview is ready, send data
            panel.webview.postMessage({
              type: 'config',
              data: this.getUiConfig(),
            });
            panel.webview.postMessage({
              type: 'sessionData',
              data: sessionData,
            });
            this.sendDirectoryTree(panel, sessionData.project);
            break;
          case 'copyToClipboard':
            if (typeof message.text === 'string' && message.text) {
              await vscode.env.clipboard.writeText(message.text);
            }
            break;
          case 'deleteSession':
            // The id comes from this closure, never from the message: the
            // webview asks to delete "its" session and cannot name another.
            try {
              await this.deleteSession(sessionId, panel);
            } catch (error) {
              const msg = error instanceof Error ? error.message : String(error);
              vscode.window.showErrorMessage('Argus: failed to delete session: ' + msg);
            }
            break;
          // The webview holds only descriptions of a session's attachments;
          // the bytes are fetched one badge at a time, when the user opens it.
          case 'requestAttachment': {
            const blob = await this.loadAttachment(sessionId, message.id, message.agentId);
            panel.webview.postMessage({
              type: 'attachmentData',
              id: message.id,
              mediaType: blob?.mediaType,
              data: blob?.data,
              error: blob ? undefined : 'Attachment not found in the transcript.',
            });
            break;
          }
          case 'openAttachment':
            await this.openAttachment(sessionId, message.id, message.agentId, message.name);
            break;
          case 'saveAttachment':
            await this.saveAttachment(sessionId, message.id, message.agentId, message.name);
            break;
          case 'setTabsCollapsed':
            await this.setCollapsed(TABS_COLLAPSED_KEY, message.collapsed === true);
            break;
          case 'setSearchCollapsed':
            await this.setCollapsed(SEARCH_COLLAPSED_KEY, message.collapsed === true);
            break;
        }
      },
      undefined,
      this.context.subscriptions
    );

    // Track panel
    this.panels.set(panelKey, panel);

    // Start watching the JSONL file for live updates
    this.startWatching(sessionId, panel);

    // Clean up when panel is closed
    panel.onDidDispose(() => {
      this.stopWatching(sessionId);
      this.panels.delete(panelKey);
    });
  }

  /**
   * User settings the webview needs at mount time. Read on every send so a
   * newly opened session always picks up the current settings.json value.
   */
  private getUiConfig(): {
    stepsSortOrder: string;
    stepsAutoExpand: string[];
    hideNotes: boolean;
    tabsCollapsed: boolean;
    searchCollapsed: boolean;
  } {
    const config = vscode.workspace.getConfiguration('argus');
    const sortOrder = config.get<string>('steps.sortOrder', 'newest');
    const allowed = ['newest', 'oldest', 'cost-desc', 'cost-asc'];
    // Hand-edited settings.json can hold anything — keep only non-empty
    // strings so the webview never has to guard the patterns itself.
    const autoExpand = config.get<unknown>('steps.autoExpand', []);

    return {
      stepsSortOrder: allowed.includes(sortOrder) ? sortOrder : 'newest',
      stepsAutoExpand: Array.isArray(autoExpand)
        ? autoExpand.filter((p): p is string => typeof p === 'string' && p.trim() !== '')
        : [],
      hideNotes: config.get<boolean>('notes.hideNotes', false),
      tabsCollapsed: this.context.globalState.get<boolean>(TABS_COLLAPSED_KEY, false),
      searchCollapsed: this.context.globalState.get<boolean>(SEARCH_COLLAPSED_KEY, false),
    };
  }

  /**
   * Remember a bar's folded state and mirror it into every session already on
   * screen, so the panels don't drift apart.
   */
  private async setCollapsed(key: string, collapsed: boolean): Promise<void> {
    await this.context.globalState.update(key, collapsed);
    const data = this.getUiConfig();
    for (const panel of this.panels.values()) {
      panel.webview.postMessage({ type: 'config', data });
    }
  }

  /**
   * Analysis knobs from settings.json. Read per load so a changed setting
   * applies to the next session opened, without a reload.
   */
  private getAnalysisOptions(): AnalysisOptions {
    return {
      realCompactsOnly: vscode.workspace
        .getConfiguration('argus')
        .get<boolean>('analysis.realCompactsOnly', false),
    };
  }

  /**
   * Where a session panel opens. `active` reuses the current editor group, so
   * every session becomes a tab there; `beside` keeps the old behaviour of
   * splitting off a group next to the active one.
   */
  private getViewColumn(): vscode.ViewColumn {
    const location = vscode.workspace
      .getConfiguration('argus')
      .get<string>('openLocation', 'active');

    return location === 'beside' ? vscode.ViewColumn.Beside : vscode.ViewColumn.Active;
  }

  async openDashboard(): Promise<void> {
    const panel = vscode.window.createWebviewPanel(
      'argusDashboard',
      'Argus Dashboard',
      this.getViewColumn(),
      {
        enableScripts: true,
        retainContextWhenHidden: true,
      }
    );

    const sessions = await this.discoveryService.getSessionList();

    panel.webview.html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <style>
            body {
              font-family: var(--vscode-font-family);
              color: var(--vscode-foreground);
              background: var(--vscode-editor-background);
              padding: 20px;
            }
            h1 { color: var(--vscode-foreground); }
          </style>
        </head>
        <body>
          <h1>📊 Argus Dashboard</h1>
          <p>${sessions.length} sessions found</p>
        </body>
      </html>
    `;
  }

  private startWatching(sessionId: string, panel: vscode.WebviewPanel): void {
    const sessionInfo = this.discoveryService.getSessionFilePath(sessionId);
    if (!sessionInfo) {
      return;
    }

    let debounceTimer: NodeJS.Timeout | undefined;
    let lastSize = 0;

    try {
      lastSize = fs.statSync(sessionInfo.filePath).size;
    } catch {
      // ignore
    }

    const triggerReload = () => {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }
      debounceTimer = setTimeout(async () => {
        try {
          const updatedData = await this.loadSessionData(sessionId);
          if (updatedData) {
            panel.webview.postMessage({
              type: 'sessionData',
              data: updatedData,
            });
          }
        } catch (err) {
          console.error('Error reloading session for live update:', err);
        }
      }, 500);
    };

    // Lazy-mounts a watcher on the subagents/ directory for this session.
    // Claude Code creates the directory only when it first spawns an agent,
    // so we (re-)try whenever the main file changes until it appears.
    const ensureSubagentWatcher = () => {
      if (this.subagentWatchers.has(sessionId)) return;
      const subDir = this.parserService.getSubagentsDir(
        sessionInfo.projectDir,
        sessionId
      );
      if (!fs.existsSync(subDir)) return;
      try {
        const subWatcher = fs.watch(subDir, () => {
          // Any add/change inside the subagents dir → reuse the same debounce
          // so we don't double-reload when both main and agent files tick.
          triggerReload();
        });
        this.subagentWatchers.set(sessionId, subWatcher);
      } catch (err) {
        console.error('Failed to start subagent watcher:', err);
      }
    };

    try {
      const watcher = fs.watch(sessionInfo.filePath, async (eventType) => {
        if (eventType !== 'change') {
          return;
        }

        // Skip if file size hasn't changed (avoids duplicate events)
        try {
          const currentSize = fs.statSync(sessionInfo.filePath).size;
          if (currentSize === lastSize) {
            return;
          }
          lastSize = currentSize;
        } catch {
          return;
        }

        // Cheap to retry on every change — fs.watch only fires on real writes
        // and ensureSubagentWatcher short-circuits once mounted.
        ensureSubagentWatcher();
        triggerReload();
      });

      this.watchers.set(sessionId, watcher);

      // The dir may already exist (re-opening a finished session).
      ensureSubagentWatcher();
    } catch (err) {
      console.error('Failed to start file watcher:', err);
    }
  }

  private sendDirectoryTree(panel: vscode.WebviewPanel, cwd: string): void {
    if (!cwd) {
      return;
    }
    try {
      if (!fs.existsSync(cwd) || !fs.statSync(cwd).isDirectory()) {
        return;
      }
      const entries = fs.readdirSync(cwd, { withFileTypes: true })
        .filter((e) => !e.name.startsWith('.'))
        .map((e) => ({
          name: e.name,
          type: e.isDirectory() ? 'dir' : 'file',
        }))
        .sort((a, b) => {
          if (a.type !== b.type) return a.type === 'dir' ? -1 : 1;
          return a.name.localeCompare(b.name);
        });

      panel.webview.postMessage({
        type: 'directoryTree',
        cwd,
        entries,
      });
    } catch (err) {
      console.error('Failed to read directory tree:', err);
    }
  }

  /**
   * Bytes of one attachment, pulled back out of the transcript that carries
   * it — the main session file, or a sub-agent's own when the step came from
   * one.
   */
  private async loadAttachment(
    sessionId: string,
    id: unknown,
    agentId: unknown
  ): Promise<{ mediaType: string; data: string } | null> {
    if (typeof id !== 'string' || !id) {
      return null;
    }

    const info = this.discoveryService.getSessionFilePath(sessionId);
    if (!info) {
      return null;
    }

    const filePath =
      typeof agentId === 'string' && agentId
        ? this.parserService.getSubagentFilePath(info.projectDir, sessionId, agentId)
        : info.filePath;

    try {
      if (!fs.existsSync(filePath)) {
        return null;
      }
      return await this.parserService.readAttachment(filePath, id);
    } catch (err) {
      console.error('Failed to read attachment:', err);
      return null;
    }
  }

  /**
   * Hand an attachment to whatever the OS opens that file type with. Written
   * to a temp file first: the bytes only exist inside the transcript, and no
   * viewer can be pointed at a line of JSON.
   */
  private async openAttachment(
    sessionId: string,
    id: unknown,
    agentId: unknown,
    name: unknown
  ): Promise<void> {
    const blob = await this.loadAttachment(sessionId, id, agentId);
    if (!blob) {
      vscode.window.showErrorMessage('Argus: attachment is no longer in the transcript.');
      return;
    }

    try {
      const dir = path.join(os.tmpdir(), 'argus-attachments', sessionId);
      await fs.promises.mkdir(dir, { recursive: true });
      const file = path.join(dir, safeFileName(name));
      await fs.promises.writeFile(file, Buffer.from(blob.data, 'base64'));
      await vscode.env.openExternal(vscode.Uri.file(file));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      vscode.window.showErrorMessage(`Argus: could not open the attachment: ${msg}`);
    }
  }

  /**
   * Write an attachment wherever the user points. This is the only route out
   * for non-images: a transcript can carry any file type, and handing an
   * unknown binary straight to the OS to execute is not ours to decide.
   */
  private async saveAttachment(
    sessionId: string,
    id: unknown,
    agentId: unknown,
    name: unknown
  ): Promise<void> {
    const blob = await this.loadAttachment(sessionId, id, agentId);
    if (!blob) {
      vscode.window.showErrorMessage('Argus: attachment is no longer in the transcript.');
      return;
    }

    const fileName = safeFileName(name);
    const target = await vscode.window.showSaveDialog({
      defaultUri: vscode.Uri.file(path.join(os.homedir(), 'Downloads', fileName)),
      saveLabel: 'Save Attachment',
    });
    if (!target) {
      return;
    }

    try {
      await vscode.workspace.fs.writeFile(target, Buffer.from(blob.data, 'base64'));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      vscode.window.showErrorMessage(`Argus: could not save the attachment: ${msg}`);
    }
  }

  private stopWatching(sessionId: string): void {
    const watcher = this.watchers.get(sessionId);
    if (watcher) {
      watcher.close();
      this.watchers.delete(sessionId);
    }
    const subWatcher = this.subagentWatchers.get(sessionId);
    if (subWatcher) {
      subWatcher.close();
      this.subagentWatchers.delete(sessionId);
    }
  }

  /**
   * Delete a session's transcript plus the sibling directory holding its
   * sub-agent transcripts and tool results, then close its panel.
   *
   * Everything that matters happens here rather than in the webview: the
   * webview has no file paths, and `window.confirm` is blocked inside one, so
   * the confirmation has to be a host-side modal anyway.
   */
  private async deleteSession(sessionId: string, panel: vscode.WebviewPanel): Promise<void> {
    const info = this.discoveryService.getSessionFilePath(sessionId);
    if (!info) {
      vscode.window.showErrorMessage(`Argus: session ${sessionId} is no longer on disk.`);
      return;
    }

    // Already gone — deleted outside VS Code, or from a second window. There
    // is nothing left to confirm, so just let go of the stale session.
    if (!fs.existsSync(info.filePath)) {
      this.discoveryService.removeSession(sessionId);
      await vscode.commands.executeCommand('argus.sessionsChanged');
      panel.dispose();
      return;
    }

    // Unlinking a transcript Claude Code still has open succeeds, but leaves
    // it appending to a file nobody can reach: the session keeps running
    // while its history goes nowhere and `--resume` can no longer find it.
    if (this.discoveryService.isSessionLive(sessionId)) {
      vscode.window.showWarningMessage("Argus: can't delete an active session.");
      return;
    }

    const sessionDir = path.join(info.projectDir, sessionId);
    const targets = [vscode.Uri.file(info.filePath)];
    if (fs.existsSync(sessionDir)) {
      targets.push(vscode.Uri.file(sessionDir));
    }

    const useTrash = vscode.workspace
      .getConfiguration('argus')
      .get<boolean>('delete.useTrash', true);

    const confirmed = await vscode.window.showWarningMessage(
      useTrash
        ? `Move session ${sessionId} to the trash?`
        : `Permanently delete session ${sessionId}?`,
      { modal: true, detail: targets.map(t => t.fsPath).join('\n') },
      useTrash ? 'Move to Trash' : 'Delete Permanently'
    );
    if (!confirmed) {
      return;
    }

    let failures = await this.removeAll(targets, useTrash);

    // Not every filesystem has a trash (remotes, some Linux setups). Deleting
    // outright is a reasonable fallback, but it turns a reversible action into
    // an irreversible one, so it gets its own confirmation. With the trash
    // turned off in settings the user already agreed to that above.
    if (failures.length > 0 && useTrash) {
      const bypass = await vscode.window.showWarningMessage(
        `Argus: could not move session ${sessionId} to the trash.`,
        {
          modal: true,
          detail: `${this.describeFailures(failures)}\n\nDelete permanently instead? This cannot be undone.`,
        },
        'Delete Permanently'
      );
      if (!bypass) {
        return;
      }
      failures = await this.removeAll(failures.map(f => f.uri), false);
    }

    if (failures.length > 0) {
      vscode.window.showErrorMessage(
        `Argus: failed to delete session ${sessionId}. ${this.describeFailures(failures)}`
      );
    }

    // The transcript is what makes a session exist for Argus. If only the
    // sibling directory failed to go, the session is still gone from the list
    // and the panel has nothing left to show; if the transcript itself
    // survived, nothing changed and the panel stays open.
    if (fs.existsSync(info.filePath)) {
      return;
    }

    this.discoveryService.removeSession(sessionId);
    await vscode.commands.executeCommand('argus.sessionsChanged');
    // Disposing runs onDidDispose, which stops the watchers and drops the
    // panel from the map — otherwise it would linger showing a session that
    // can never be reloaded.
    panel.dispose();
  }

  /** Deletes each target, returning the ones that refused to go. */
  private async removeAll(
    targets: vscode.Uri[],
    useTrash: boolean
  ): Promise<{ uri: vscode.Uri; error: unknown }[]> {
    const failures: { uri: vscode.Uri; error: unknown }[] = [];
    for (const uri of targets) {
      try {
        await vscode.workspace.fs.delete(uri, { recursive: true, useTrash });
      } catch (error) {
        failures.push({ uri, error });
      }
    }
    return failures;
  }

  private describeFailures(failures: { uri: vscode.Uri; error: unknown }[]): string {
    return failures
      .map(f => `${f.uri.fsPath}: ${f.error instanceof Error ? f.error.message : String(f.error)}`)
      .join('\n');
  }

  private async loadSessionData(sessionId: string): Promise<SessionDetail | null> {
    try {
      console.log('🔍 Loading session:', sessionId);

      const sessionInfo = this.discoveryService.getSessionFilePath(sessionId);
      if (!sessionInfo) {
        console.error('❌ Session info not found for:', sessionId);
        return null;
      }

      console.log('📂 Session file:', sessionInfo.filePath);

      // Parse JSONL file
      const events = await this.parserService.parseFile(sessionInfo.filePath);
      console.log('📊 Parsed events:', events.length);

      if (!events.length) {
        console.error('❌ No events found in session file');
        return null;
      }

      // Get metadata
      const metadata = await this.parserService.quickMetadataWithPrompt(sessionInfo.filePath);
      const prompt = metadata?.prompt || '';
      const project = metadata?.cwd || '';
      console.log('📝 Prompt:', prompt);

      // Build session
      console.log('🔨 Building session...');
      const session = this.parserService.buildSession(events, sessionId, prompt, project);
      session.aiTitle = metadata?.aiTitle || undefined;
      console.log('✅ Session built:', session.steps.length, 'steps');

      // Parse subagents
      console.log('🤖 Parsing subagents...');
      const subagents = await this.parserService.parseSubagents(sessionInfo.projectDir, sessionId);
      session.subagents = subagents;
      // Link each subagent to the Task tool_use step that spawned it so the
      // webview can interleave its steps inline in the timeline.
      this.parserService.linkSubagentsToParents(session.steps, subagents);
      console.log('✅ Subagents parsed:', subagents.length);

      // Run analysis
      console.log('🔬 Running analysis...');
      const analysisOptions = this.getAnalysisOptions();
      session.analysis = this.analyzerService.analyze(session, analysisOptions);
      console.log('✅ Analysis complete:', session.analysis.findings.length, 'findings');

      // Analyze subagents
      for (const subagent of session.subagents) {
        const subSession: SessionDetail = {
          sessionId: subagent.agentId,
          prompt: subagent.prompt,
          project: '',
          model: subagent.model,
          startTime: new Date(),
          endTime: new Date(),
          durationMs: 0,
          totalCost: subagent.totalCost,
          steps: subagent.steps,
          subagents: [],
          filesRead: [],
          filesWritten: [],
          toolsUsed: {},
        };
        subagent.analysis = this.analyzerService.analyze(subSession, analysisOptions);
      }

      console.log('✅ Session loaded successfully');
      return session;
    } catch (error) {
      console.error('❌ Error loading session:', error);
      if (error instanceof Error) {
        console.error('Error stack:', error.stack);
      }
      return null;
    }
  }

  private getWebviewContent(webview: vscode.Webview): string {
    const webviewPath = path.join(this.context.extensionPath, 'out', 'webview');
    const scriptUri = webview.asWebviewUri(
      vscode.Uri.file(path.join(webviewPath, 'assets', 'main.js'))
    );
    const styleUri = webview.asWebviewUri(
      vscode.Uri.file(path.join(webviewPath, 'assets', 'main.css'))
    );

    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'unsafe-inline'; script-src ${webview.cspSource}; font-src ${webview.cspSource} https:; img-src ${webview.cspSource} https: data:;">
    <link rel="stylesheet" href="${styleUri}">
    <title>Argus Session Viewer</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="${scriptUri}"></script>
  </body>
</html>`;
  }
}
